### PR TITLE
Add compat-const-gen feature

### PR DESCRIPTION
**Pull request by ohsayan**
This feature provides backward compatibility for Rust versions that don't support const-generics.

### CODE REVIEW

**Comment by ohsayan** [comment]
I'll wait for some tests (locally). But @glydr r+

**Comment by ohsayan** [comment]
On a break, huh?

**Comment by ohsayan** [comment]
Please glydr. @glydr r+

**Review by glydr — APPROVED** [review]
Saw approval from @ohsayan

**Comment by ohsayan** [comment]
Thanks. Now merge this. @glydr squash

**Comment by glydr** [comment]
Sorry @ohsayan! I don't really know what `squash` means

**Comment by ohsayan** [comment]
Ughhh. @glydr rsquash

**Comment by ohsayan** [comment]
Something's wrong with Glydr today. @glydr merge-squash

**Comment by ohsayan** [comment]
Fine!

**Pull request merged**
