### PR TITLE
Update README to use SkyResult in example code

### PR DESCRIPTION
**Pull request by neliusdelange**
Thank you for your work on SkyTable.
When looking at the Rust Client, I noticed the current example code, did not compile because of the Result return type.

use skytable::{Connection, Query, Element};
fn main() -> std::io::Result<()> {
    let mut con = Connection::new("127.0.0.1", 2003)?;
    Ok(())
}

I updated the example to use 'SkyResult' instead.

Thank you
Nelius

### CODE REVIEW

**Comment by glydr** [comment]
[CLA assistant check](https://cla.skytable.io/skytable/client-rust?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.skytable.io/skytable/client-rust?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.skytable.io/check/skytable/client-rust?pullRequest=14) it.</sub>

**Comment by ohsayan** [comment]
Sorry I missed this 😅. Can you please sign the CLA above and I'll merge it ASAP :)

**Comment by neliusdelange** [comment]
Hi, no worries.
I did sign the CLA on the redirect page to cla.skytable.io, but it seems that Github is not picking it up. 
image

**Comment by ohsayan** [comment]
Oops. I'll merge it then. Thanks for noticing this :)

**Pull request merged**
